---
title: "EVPPI example"
output: html_document
---

## Set up

```{r set up,echo=F}
library(mgcv); 
library(knitr)

nSamples <- 5000
```

## Compute model
Use saved example, or compute anew: 

```{r load or compute parameters and results,echo=F}

saved_example <- paste0('evppi_example_',nSamples,'_samples.Rds')
if(file.exists(saved_example)){
  
  example <- readRDS(saved_example)
  parameter_samples <- example$parameter_samples
  result <- example$result
  
  cat(paste0('Using example saved as ',saved_example))
}else{
  
  library(distr)
  source('pollution_model_functions.R')
  cat(paste0('Loading computation functions from pollution_model_functions.R'))
  
  ## VARIABLES ##
  parameters <- get_parameters()
  ## CONSTANTS ##
  const <- readRDS('constants.Rds')
  cat(paste0('Loading constants from constants.Rds'))
  
  parameter_samples <- matrix(0,nrow=nSamples,ncol=length(parameters))
  result <- matrix(0,nrow=nSamples,ncol=length(parameters))
  for(j in 1:nSamples){
    pollution_return <- pollution_calculation(const,parameters)
    parameter_samples[j,] <- pollution_return$parameter_samples
    result[j,] <- pollution_return$scenario_burden
  }
  colnames(parameter_samples) <- names(parameters)
  
  saveRDS(list(parameter_samples=parameter_samples,result=result),saved_example)
  cat(paste0('Saving results to ',saved_example))
  
}
```

## Results
### Compute result
EVPPI is evaluated by regressing the outcome against each parameter in turn. 

```{r univariate EVPPI}
# initialise empty matrix for evppi results
evppi <- matrix(0,ncol=ncol(result)-1,nrow=ncol(parameter_samples))
# loop over results, held in columns, omitting the first (baseline)
for(j in 2:ncol(result)){
  # extract outcome vector y
  y <- result[,j]
  # compute variance
  vary <- var(y)
  for(i in 1:ncol(parameter_samples)){
    # extract parameter vector x
    x <- parameter_samples[,i];
    # write y as a smooth model of x
    model <- gam(y~s(x)); 
    # compute variance in prediction
    pred_var <- mean((y-model$fitted)^2)
    # calculate raw evppi as the expected reduction in variance
    raw_evppi <- vary-pred_var
    # calculate evppi as a percentage of observed variance
    evppi[i,j-1] <- raw_evppi/vary*100;
  }
}
```

### Present result
```{r EVPPI vector,echo=F}
scenarios <- c('Scenario 1','Scenario 2')
labels <- c('Background PM2.5','Car fraction','Dose-response estimate')
colnames(evppi) <- scenarios
rownames(evppi) <- labels
kable(evppi,digits=1)
```

```{r plot,echo=F}
cols <- c('navyblue','hotpink')
par(mar=c(12.5,5,1,1))
x <- barplot(t(evppi),beside=T,names.arg=labels,las=2,cex.names=1.25,cex.lab=1.25,cex.axis=1.25,col=cols,ylab='EVPPI, % of Var(DALY)')
legend(legend=scenarios,x=2,y=max(evppi),bty='n',fill=cols)
```
